### ISSUE TITLE
Most code examples not working

### ISSUE THREAD

**Issue by annie-annie** [erikras/redux-form-docs#1]
Only these two code example pages work. The rest error and do not render.
https://redux-form.com/8.1.0/examples/immutable/ 
https://redux-form.com/8.1.0/examples/react-widgets/

**Comment by leanrob** [comment]
I can second this. The latest version of the docs has almost all examples failing. With the following error in the console.

`Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(ReduxForm(u))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(ReduxForm(u))".`

**Comment by annie-annie** [comment]
Works now, all is good
